hubble:
  metrics:
    dashboards:
      annotations:
        grafana_folder: Hubble
      enabled: true
      namespace: monitoring
    enableOpenMetrics: true
    service:
      type: ClusterIP
      port: 9965
    enabled:
    - dns
    - drop
    - tcp
    - icmp
    - flow:sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity
    - kafka:labelsContext=source_namespace,source_workload,destination_namespace,destination_workload,traffic_direction;sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity
    - httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction;sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity
    serviceMonitor:
      enabled: true
  relay:
    enabled: true
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
    service:
      type: NodePort
  ui:
    enabled: true
    service:
      type: NodePort
ipam:
  mode: kubernetes
ipv4NativeRoutingCIDR: 10.244.0.0/18
k8sServiceHost: 192.168.82.9
k8sServicePort: 6443
kubeProxyReplacement: true
operator:
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
  replicas: 1
prometheus:
  enabled: true
  serviceMonitor:
    trustCRDsExist: true
    enabled: true
routingMode: tunnel
tunnelProtocol: vxlan
