networkPolicy:
  enabled: true
  enableHTTPIngressVisibility: true
  enableKafkaEgressVisibility: false

recruiter:
  replicas: 1

jobposting:
  replicas: 1

coreapi:
  replicas: 1
  # how often the API should return errors
  errorRate: 0.01
  # how often the API should delay requests
  sleepRate: 0.1
  sleepLowerBound: 0.1
  sleepUpperBound: 0.2

crawler:
  replicas: 1
  crawlFrequencyLowerBound: 0.5
  crawlFrequencyUpperBound: 5.0

resumes:
  replicas: 1

loader:
  replicas: 1

kafka:
  replicas: 1

kafkaTopic:
  partitions: 2

elasticsearch:
  imageTag: 7.17.26

strimzi-kafka-operator:
  extraEnvs:
    - name: STRIMZI_KUBERNETES_VERSION
      value: "major=1,minor=33"
